name: ubuntu

on:
  push:
  pull_request:

jobs:

  ubuntu:
    name: ubuntu
    runs-on: ubuntu-20.04
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: ubuntu
        run: |
          ./setup.sh
